title: Prafulla Dhariwal
description: Personal Website and Blog
author: "Prafulla Dhariwal"
email: prafullasd@gmail.com

url: https://prafulladhariwal.com
plugins:
  - jekyll-sitemap

theme: minima

# Minima social links
scholar_username: 0pOgVVAAAAAJ
twitter_username: prafdhar
linkedin_username: prafulladhariwal

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md

include:
    - _pages
    - _media
    - _posts

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

defaults:
  - 
    scope:
      path: "_pages/publications*"
    values:
      sitemap: false
  - 
    scope:
      path: "_pages/media*"
    values:
      sitemap: false