title: Prafulla Dhariwal
description: Blog
author: "Prafulla Dhariwal"

theme: minima

# Minima social links
twitter_username: prafdhar
github_username: prafullasd
linkedin_username: prafulladhariwal

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/publications.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
