title: Prafulla Dhariwal
description: Personal Website and Blog
author: "Prafulla Dhariwal"
email: prafullasd@gmail.com

url: https://prafulladhariwal.com

theme: minima

# Minima social links
scholar_username: 0pOgVVAAAAAJ
twitter_username: prafdhar
linkedin_username: prafulladhariwal

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/publications.md
  - _pages/media.md
  - _pages/archive.md

include:
    - _pages
    - _media

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

